# Doc: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/
---
apiVersion: v1
kind: Pod
metadata:
  name: window-manager
spec:
  volumes:
    - name: xorg-socket
      hostPath:
        path: /tmp/.X11-unix/
  restartPolicy: Never
  containers:
    - name: twm
      image: localhost/silverkube
      imagePullPolicy: Never
      stdin: true
      tty: true
      env:
        - name: DISPLAY
          value: ":0"
      volumeMounts:
        - mountPath: "/tmp/.X11-unix"
          name: xorg-socket
      command: ["/bin/twm"]
