# Doc: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/

---
apiVersion: v1
kind: Pod
metadata:
  name: display-server
spec:
  volumes:
    - name: xorg-socket
      hostPath:
        path: /tmp/.silverkube/xorg
    - name: tty
      hostPath:
        path: /dev/tty1
    - name: dri
      hostPath:
        path: /dev/dri
    - name: input
      hostPath:
        path: /dev/input
    - name: udev
      hostPath:
        path: /run/udev
  restartPolicy: Never
  containers:
    - name: xorg
      image: localhost/silverkube
      imagePullPolicy: Never
      stdin: true
      tty: true
      securityContext:
        # privileged: true
        runAsUser: 1000
        runAsGroup: 1000
        seLinuxOptions:
          type: silverkube.process
      volumeMounts:
        - mountPath: "/tmp/.X11-unix"
          name: xorg-socket
        - mountPath: "/dev/tty1"
          name: tty
        - mountPath: "/dev/dri"
          name: dri
        - mountPath: "/dev/input"
          name: input
        - mountPath: "/run/udev"
          name: udev
      command: ["/bin/Xorg", "-sharevts", "vt1", "-keeptty"]
#      command: ["/bin/sleep", "Inf"]

---
apiVersion: v1
kind: Pod
metadata:
  name: window-manager
spec:
  volumes:
    - name: xorg-socket
      hostPath:
        path: /tmp/.silverkube/xorg
  restartPolicy: Never
  containers:
    - name: twm
      image: localhost/silverkube
      imagePullPolicy: Never
      stdin: true
      tty: true
      securityContext:
        # privileged: true
        runAsUser: 1000
        runAsGroup: 1000
        seLinuxOptions:
          type: silverkube.process
      env:
        - name: DISPLAY
          value: ":0"
      volumeMounts:
        - mountPath: "/tmp/.X11-unix"
          name: xorg-socket
      command: ["/bin/twm"]
