- hosts: all
  gather_facts: no
  vars:
    ci_tracer_args: "--cgroup 'silverkube-*' --interval 100"
  roles:
    - build
    - run-ci-tracer
    - deploy
    - benchmark
    - generate-ci-tracer-report
